const quotes = [
    { content: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { content: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
    { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { content: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { content: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { content: "Act as if what you do makes a difference. It does.", author: "William James" },
    { content: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { content: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { content: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
    { content: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
    { content: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { content: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { content: "The best way to predict the future is to invent it.", author: "Alan Kay" },
    { content: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { content: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
    { content: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { content: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
    { content: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { content: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Anonymous" },
    { content: "Great things never come from comfort zones.", author: "Anonymous" },
    { content: "Dream it. Wish it. Do it.", author: "Anonymous" },
    { content: "Little things make big days.", author: "Anonymous" },
    { content: "It's going to be hard, but hard does not mean impossible.", author: "Anonymous" },
    { content: "Sometimes later becomes never. Do it now.", author: "Anonymous" },
    { content: "Success doesn't just find you. You have to go out and get it.", author: "Anonymous" },
    { content: "Dream bigger. Do bigger.", author: "Anonymous" },
    { content: "Wake up with determination. Go to bed with satisfaction.", author: "Anonymous" },
    { content: "The key to success is to focus on goals, not obstacles.", author: "Anonymous" },
    { content: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { content: "Work hard in silence, let your success be the noise.", author: "Frank Ocean" },
    { content: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { content: "What we think, we become.", author: "Buddha" },
    { content: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford" },
    { content: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    { content: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { content: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    { content: "Life is not about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
    { content: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { content: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    { content: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    { content: "The best revenge is massive success.", author: "Frank Sinatra" },
    { content: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
    { content: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { content: "Nothing is impossible. The word itself says 'I'm possible!'", author: "Audrey Hepburn" },
    { content: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { content: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison" },
    { content: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { content: "You have power over your mind - not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
    { content: "It is never too late to be what you might have been.", author: "George Eliot" },
    // Add more here for a total of 100!
];
